language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - develop
    - '/^v.*$/'
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    edge: true
    skip_cleanup: true
    api_key:
      secure: R3zhKKSwrIiWp7OV+mDVeKcNG7n9MVMvzjScjmiW6jE/nY+WLQAjruh3dKledb9s5xv+mIQ8zoarkhbcxSWpnv/c1zyLbhq5xz2oZHwmLeNsRYSzlHLzv3ZnlIExZ3Ei4a2y6Tk0JZa2ywncM8wKocM49Z+AJOxU5Z4rN0vHz+F7jdAJmY5HlvZ5U68S8xXdhWjRs87Ptqr5aMvPT0UppHmOV3ODehRI/xUJIIy/uAXbpLXPX+SdhdP76YrCswwZXKuXdCsZeebWUPAB/VTEhvaTKfF6ST0jJhM1f2CfZbeTkqQyxr0L0HH/BlqxJsmEMFXNX9f0tsHCE2YSo7HJAcWpYMBezZd9E4oj8PQ8dD8niuj6vS6+SwV5wMV/ce2ptM+/xH3QvlWy69jHvHl5ymReCcLS6uJPJDR8FqE9RHw7v5NLb78VOvcuCwN1ewlrOhjAKRbiRa1cCGJbH9oJfS9BPfJecCGS23dEINLg/znnP/Chgd9aHVnejVBuRXScTxrb1czFzttt/RPxv8+0P2WaxCvNWzafpbHP9bx2HCDDJLKsmMt6ZZQmdKzop141CxU4dRe6WRiuKYJIvspsofj84jcWzUQgMGdqKhqGPzz4QzlosRsZ+uKe/LionwpiiA/KmJHf+cnbBaAxdm+bcGLST0jT7yoK8nmfx+MILKA=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/piling.js
  - provider: npm
    edge: true
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: BlDZ1pX9NPtuUr2UYToQGBUZMC9TA5EOnQJaX5/h/sCc4BZpjX7QqVvDNfy5UoR//6aLQLkYjMJgtfGqvZ39DgkoeUidQ17O5YB9PODgRNTzVOChflvdx1wdhibOYUgRHT/BFVX2aAglPCQBPUIx01Fa2s+yy68s/3c3ReUvnjdUC3pTHYUh7SnMfAjNzg3V5pw2rl5hpbKV2w3da97prynpV6w7QqS8DYjBRrvCW37PSZXY5lJ7EgdSRaRLvp/8cVW21p1vms4kXMT66IMXnNgkm7sVXK7vU3wowTsXPQeRPt2MPE2yYFhRW0dIqV4HcQO73N7Trfx1Yuc8ZEi3HBqEb5CWSmmwMISjRUJ2awr93WXK9rEFKll3A0496QzBg5HuiX7ppgvH8cf81FcPjpLc5ZMIvSkTDjuiovJ9sr6MBci7TsZEcY6lbXXXMswrAb+yb1BauYWIVe5ns2Lh7PCTImvuqQrUav4KWq5JxqgKbmzUuRkQ9s62B9VSmdNpFCbigTd/K8+dFDnW88HxYrq4lVXMAqfPg3NHLB3hdvxqGROt5GFMUet1I3J2ijgv4U8L3sXLGZgudJv0NxrkkQ/KI7ACQfrz0KX6VXKgWItLUooVMradST6Wv18of+3B5MIAAoNU28HrEMfRRe5lyw74JrYqdJEet4hv2HE+Fno=
    on:
      branch: master
      tags: true
      repo: flekschas/piling.js
