language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - develop
    - '/^v.*$/'
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: CpfM7VFcyATakJW/uoCFtZdQrijjFXX1+ESOODUDsLVYV9Ukdgi9M2g3J1CJDdOD11kgOUdwihZHXIGEWlWQXsLjcECncm/+xYzhcrZV/+JzV4zbGBw7KIwrOksqBXY8WeS1nH0PJULFtcMWH7TsU/wrY7Oyrpqr26IOzhDlDhAyKzPtEJBPT5v2r9cD4zUMcUGbfezciktEgwDzr+mXtr1AyNDxdyzIbnjGM/6Nom/Z+B8i+liYyCo5ROBKzV/w8raG8fb6DR68FXQIjPac0mU3yDU41qQ1t4/1AhNQlAZNoZ0JpbHMg2NFOfjoq4AlpfGvHkBxV3INuhJ5p4dNc1OR/gkUwbj7XJVzAyvtYw6GCLs37IoJxbQDeEX0cXaTrkK8awiM9A2a0ItB9acNVP968hHYDKgCwsPzfxTIESvXDnWJYdKyt0BFoEO/+u2OAb5blTxWqfv7frV/+dHidbqlqAbN8YYA2PhXh2CdXkoU44OzBG7KmAgvOlLCHR5JpyJXnesk94DKLzHENHqiiyhRyqwITn3TY1Oe/wj+Rw32Q40RM+pmFptsVvG/vahBOAsrbTuRe6USgQrr4jh6Mah9UIRFL6Gdyyt0ceMpF0gA3C+HG2bDfCBJpeAvZhBc1GAG2n80PAXNeDMkkkQ7cjMWPGMhYhYvlB3ut3EaSN0=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/piling.js
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: YIhv6hWb9CnWsd6o/jPl09mYd3fa0UETSl3Ga0PXIG/0ccbBPqkP4T5qbxhHR20ag33f6KtKWp1Ju9ktORuPfwofMsjCXbbSf9/HjD31l6sWKvl9vWWtz3rRyY/WJS9k0V0jrUED+JBxSocJp/oJfvz9XGed4iLoJC9q7rSNrOnOnNbIWcYdGmTAVPrENIg0bSFe/udNpa2Jgs7OItk/Gdeqba0hlARb4f8TMecSgoSL9yKmgZwquUKnT9zlzId2tpw3a+Ab1sflOiaBz+5g3yR/MZENJFCwXvAEgzAZOMtdmRz5iSPRx3SJyhT+CrewYMhg+x+J0oIgWEF1qSyTOWgR0zKNNXrkYaBZcDpsIlGNxeklnqqz9wRhL8ti5hMGPPkMDD03XVOyJPvOXh/PFgFBzkCA06XP90pJXCzTWTzwh9+iu77IDO/6xpOWRtixI3OnbiLLUKve9eOluGhMXgrQoiE0ZWoJYhYLr2uFoxskEvnIXras31fMbjw2x64w1yLptMqsjIsDQWRLtHz8yQkac4hH/W2O5x9Ap41T5IvS6s7vjrNmESNbxbmdJhwlbeSQ8mpsifRunaPMyH6E62vrZ4q6iO2mj1MklH+lfUbEuxJHAcdGQropmI3TAQeG6rLm3VVMvudktqP7AFFLnQEE9Q3HFaBwHgUMCDu+u/4=
    on:
      branch: master
      tags: true
      repo: flekschas/piling.js
