name: pilingjs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - imageio
  - matplotlib
  - numba
  - pip
  - scikit-image
  - scikit-learn
  - umap-learn
  - jupyterlab
  - pip:
      - apricot-select
      - ndjson
      - pycountry
